# 视频存储位置
SavePath_Sub: "/mnt/mac/SATA_SSD_2T/000-NASSAV/000-Sub/"
SavePath_noSub: "/mnt/mac/SATA_SSD_2T/000-NASSAV/000-noSub/"
SavePath_Javle_Sub: "/mnt/mac/SATA_SSD_2T/000-NASSAV/000-JableSub/"
SavePath_rou_video: "/mnt/mac/SATA_SSD_2T/000-NASSAV/000-Rou/"

# 抓取网站用的代理
Proxy_Catch: "http://10.10.10.88:7890"

# 下载用的代理
Proxy_Download: "http://10.10.10.88:7890"

# 是否启用代理
IsNeedCurlProxy: "y"
IsNeedDownloadProxy: "y"

# 使用的下载器 (只能一个，默认 N_m3u8DL-RE)
N_m3u8DL_RE: "y"
yutoo: "y"

# 数据源（仅针对 AV）及调用顺序
DataSources:
  - name: JavDB
    order: 1
    urls:
      - "https://javdb.com"

  - name: JavBus
    order: 1
    urls:
      - "https://javbus.com"

JAV_Video_DataSources:
  - name: Jable
    order: 1
    urls:
      - "https://jable.tv/videos"

  - name: NetFlav
    order: 2
    urls:
      - "https://netflav.com"

  - name: AvToday
    order: 3
    urls:
      - "https://avtoday.io"

  - name: MissAV
    order: 4
    urls:
      - "https://missav.ai"


  - name: HohoJ
    order: 0
    urls:
      - "https://hohoj.tv"

  - name: Memo
    order: 0
    urls:
      - "https://memojav.com"

  - name: KissAv
    order: 0
    urls:
      - "https://f15.bzraizy.cc"
