# version: "3.9"
services:
  Movie_SP:
    image: movie_sp_env:latest
    volumes:
      - /Users/super/Documents/DockerData/Movie_SP/:/app/
      - /Volumes/SATA_SSD_2T/:/DRIVE
    ulimits:
      nofile:
        soft: 1048000
        hard: 1048000

  Jable_cnSUB:
    image: movie_sp_env:latest
    volumes:
      - /Users/super/Documents/DockerData/Movie_SP/:/app/
      - /Volumes/SATA_SSD_2T/:/DRIVE
    ulimits:
      nofile:
        soft: 1048000
        hard: 1048000
